version: 2.1
docker:
  image: circleci/node:12.8.0-stretch
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run:
                command: npm test
                no_output_timeout: 3m
workflows:
    build-and-test:
      jobs:
        - build-and-test